/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  Technology: [{
      type: 'category',
      label: 'Technology',
      link: {
        type: 'generated-index',
        title: 'Technology',
        description:
          "A collection of Technology and Developments",
          keywords: ['guides'],
          image: '/img/docusaurus.png',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'Technology'
      }],
    }
  ],
  ChineseBlog: [{
      type: 'category',
      label: 'Chinese',
      link: {
        type: 'generated-index',
        title: '中文博客',
        description:
          "Some Thoughts 💡 In Chinese",
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'Chinese'
      }]
    }
  ],
  Profolio: [{
      type: 'category',
      label: 'Profolio',
      link: {
        type: 'generated-index',
        title: 'Profolio',
        description:
          "These are collections of my works over the years",
          keywords: ['guides'],
          image: '/img/docusaurus.png',
      },
      items: [
        {
        type: 'autogenerated',
        dirName: 'Profolio'
      }],
      collapsed: false
    }
  ],
  Product: [{
      type: 'category',
      label: 'Product',
      link: {
        type: 'generated-index',
        title: 'Product',
        description:
          "A collection of Product and Business reviews",
          keywords: ['guides'],
          image: '/img/docusaurus.png',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'Product'
      }],
    }
  ],
};

module.exports = sidebars;
