/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  Algorithms: [
    {
      type: 'autogenerated',
      dirName: 'Algorithms', // '.' means the current docs folder
    },
  ],
  DataStructures: [
    {
      type: 'autogenerated',
      dirName: 'DataStructures', // '.' means the current docs folder
    },
  ],
  Language: [
    {
      type: 'autogenerated',
      dirName: 'Language', // '.' means the current docs folder
    },
  ],
  Patterns: [
    {
      type: 'autogenerated',
      dirName: 'Patterns', // '.' means the current docs folder
    },
  ],
  DailyLogs: [{
      type: 'category',
      label: 'Logs',
      link: {
        type: 'generated-index',
        title: 'Carl\'s Daily Logs',
        description:
          "Some Thoughts 💡 In English and Chinese",
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'DailyLogs'
      }]
    }
  ],
  Photography: [{
      type: 'category',
      label: 'Photography',
      link: {
        type: 'generated-index',
        title: 'Photography',
        description:
          "These are collections of my photography works over the years",
          keywords: ['guides'],
          image: '/img/docusaurus.png',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'Photography'
      }],
      collapsed: false
    }
  ],
  Product: [{
      type: 'category',
      label: 'Product',
      link: {
        type: 'generated-index',
        title: 'Product',
        description:
          "A collection of Product and Business reviews",
          keywords: ['guides'],
          image: '/img/docusaurus.png',
      },
      items: [{
        type: 'autogenerated',
        dirName: 'Product'
      }],
    }
  ],
};

module.exports = sidebars;
