/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  Algorithms: [
    {
      type: 'autogenerated',
      dirName: 'Algorithms', // '.' means the current docs folder
    },
  ],
  DataStructures: [
    {
      type: 'autogenerated',
      dirName: 'DataStructures', // '.' means the current docs folder
    },
  ],
  Language: [
    {
      type: 'autogenerated',
      dirName: 'Language', // '.' means the current docs folder
    },
  ],
  Patterns: [
    {
      type: 'autogenerated',
      dirName: 'Patterns', // '.' means the current docs folder
    },
  ],
};

module.exports = sidebars;
